### ISSUE TITLE
Please support AuditTo

### ISSUE THREAD

**Issue by hubo0831** [serilog/serilog-sinks-async#43]

**Comment by nblumhardt** [comment]
This wouldn't make sense in the context of this sink, since `AuditTo` forces exceptions to synchronously propagate from logging methods like `Information()`. The goal of this sink is to speed up the application thread by shifting logging work to an asynchronous, background thread.

Hope this clarifies it! Let me know if you need more info.

**Comment by hubo0831** [comment]
I see,thanks!
